services:
  php-cli:
    env_file: .env
    build:
      context: docker/php
      target: edm-php
      args:
        IMAGE_VERSION: 8.3
        DOCKER_USER_ID: $DOCKER_USER_ID
        DOCKER_USER_NAME: $DOCKER_USER_NAME
        DOCKER_GROUP_ID: $DOCKER_GROUP_ID
        DOCKER_GROUP_NAME: $DOCKER_GROUP_NAME
    volumes:
      - ./app:/app
    entrypoint: bash
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - nginx

  php-fpm:
    env_file: .env
    build:
      context: docker/php
      target: edm-php
      args:
        IMAGE_VERSION: 8.3-fpm
        DOCKER_USER_ID: $DOCKER_USER_ID
        DOCKER_USER_NAME: $DOCKER_USER_NAME
        DOCKER_GROUP_ID: $DOCKER_GROUP_ID
        DOCKER_GROUP_NAME: $DOCKER_GROUP_NAME
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/app

  nginx:
    image: nginx:1.11.10
    depends_on:
      - php-fpm
    ports:
      - "${NGINX_EXTERNAL_PORT:-8080}:8080"
    volumes:
      - ./app:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  crontab:
    env_file: .env
    build:
      context: docker/php
      target: edm-php-cron
      args:
        IMAGE_VERSION: 8.3
        DOCKER_USER_ID: $DOCKER_USER_ID
        DOCKER_USER_NAME: $DOCKER_USER_NAME
        DOCKER_GROUP_ID: $DOCKER_GROUP_ID
        DOCKER_GROUP_NAME: $DOCKER_GROUP_NAME
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/app
      - ./docker/php/crontab:/var/spool/cron/crontabs/${DOCKER_USER_NAME}

  db:
    env_file: .env
    volumes:
      - ./docker/var/db:/var/lib/mysql:cached
    ports:
      - "${MARIADB_EXTERNAL_PORT:-3306}:3306"
    image: mariadb
    restart: always